export const ojCmsPage = {
  ru: {
    seoTitle: "OJ CMS на Payload — контент, каталог, заявки и аналитика",
    seoDescription: "OJ CMS на базе Payload: рабочее внедрение на сайте КЭМЗ. Редактирование каталога и новостей, заявки в панели и статистика через API Яндекс Метрики.",
    hero: {
      eyebrow: "OJ CMS / УПРАВЛЕНИЕ КОНТЕНТОМ",
      title: "Сайтом удобно управлять и после запуска",
      lead: "OJ CMS — моя система на базе Payload для работы команды с сайтом. На КЭМЗ она уже управляет каталогом, новостями и документами, сохраняет обращения и показывает статистику Яндекс Метрики. Для каждого проекта настраиваю разделы, поля и права под задачи бизнеса.",
      primary: "Попробовать демо",
      secondary: "Обсудить внедрение",
      note: "Демо размещено на Vercel: в некоторых сетях оно может не открыться без VPN. Изменения сохраняются только в вашем браузере; демо не подключено к вашему сайту.",
    },
    benefits: {
      label: "01 / ДЛЯ КОМАНДЫ",
      title: "Контент меняется без очереди к разработчику",
      intro: "Редактору нужны понятные действия и видимый результат. Разделы OJ CMS собраны вокруг обычной работы с сайтом:",
      items: [
        { title: "Страницы", text: "Меняйте заголовки, тексты, изображения и SEO-описания в одном редакторе." },
        { title: "Новости", text: "Готовьте публикации и держите материалы сайта в отдельном разделе." },
        { title: "Медиа", text: "Загружайте изображения, задавайте описания и находите нужный файл в библиотеке." },
        { title: "Черновик и предпросмотр", text: "Сохраните правку, посмотрите страницу и публикуйте её отдельным действием." },
        { title: "Настройки", text: "Обновляйте контакты, название сайта и навигацию без правки кода." },
      ],
    },
    workflow: {
      label: "02 / РАБОЧИЙ СЦЕНАРИЙ",
      title: "От правки до публикации — три понятных шага",
      intro: "Это реальные экраны демонстрации OJ CMS. Откройте её и повторите путь редактора.",
      steps: [
        { number: "01", title: "Найдите материал", text: "На главном экране видны разделы и недавние изменения.", image: "/projects/oj-cms/dashboard.webp", alt: "Обзор разделов и изменений в демонстрации OJ CMS" },
        { number: "02", title: "Внесите правку", text: "Редактор помогает сохранить черновик и предупреждает о несохранённых изменениях.", image: "/projects/oj-cms/editor.webp", alt: "Редактирование страницы в демонстрации OJ CMS" },
        { number: "03", title: "Проверьте медиа", text: "Изображения лежат в библиотеке; использованный на сайте файл нельзя удалить случайно.", image: "/projects/oj-cms/media.webp", alt: "Медиатека в демонстрации OJ CMS" },
      ],
    },
    payload: {
      label: "03 / ТЕХНОЛОГИЯ",
      title: "OJ CMS и Payload: как они связаны",
      intro: "Payload — open-source CMS: серверное хранение, API и правила доступа. OJ CMS использует эту основу и дополняет её моим интерфейсом, обзорной панелью и сценариями под конкретную команду. На сайте КЭМЗ связка уже работает с каталогом, обращениями и Яндекс Метрикой. Отдельное браузерное демо показывает редакторский сценарий без подключения к данным завода.",
      points: [
        { title: "Основа — Payload", text: "Его коллекции и поля задают структуру страниц, статей, товаров и других материалов. Исходный код открыт." },
        { title: "Слой OJ CMS", text: "Я проектирую поверх этой основы более понятный редактор: быстрый доступ к материалам, черновики, предпросмотр и защиту от случайных действий." },
        { title: "Права и версии", text: "При рабочем внедрении настраиваю доступ сотрудников и порядок публикации; Payload поддерживает версии и черновики." },
        { title: "Связь с сайтом", text: "Через API опубликованный контент попадает в публичный сайт с индивидуальным дизайном." },
      ],
      docs: "Посмотреть возможности Payload",
      docsHref: "https://payloadcms.com/docs/configuration/collections",
    },
    boundary: {
      label: "04 / ЧТО УЖЕ РАБОТАЕТ",
      title: "Демо для знакомства. Внедрение — для работы.",
      demoTitle: "Сейчас в демо",
      demoText: "Можно редактировать страницы и новости, работать с медиа, сохранять черновик и открывать предпросмотр. Данные остаются в браузере посетителя; переключение роли показывает интерфейс, но не заменяет серверную авторизацию.",
      productionTitle: "Уже работает на КЭМЗ",
      productionText: "Каталог, категории, новости и документы хранятся на сервере Payload. В OJ CMS доступны статусы публикации, заявки с сайта и статистика через API Яндекс Метрики. Для вашего проекта состав разделов и интеграций настрою отдельно.",
    },
    fit: {
      label: "05 / ПРИМЕНЕНИЕ",
      title: "Когда такой редактор полезен",
      items: [
        { title: "Корпоративный сайт", text: "Команда обновляет услуги, кейсы, новости и контакты без задач на каждую мелкую правку." },
        { title: "Каталог", text: "Товары, характеристики, категории и изображения требуют структуры и понятного процесса обновления." },
        { title: "Контентный проект", text: "Несколько авторов готовят материалы, проверяют изменения и публикуют по согласованным правилам." },
      ],
    },
    delivery: {
      label: "06 / ВНЕДРЕНИЕ",
      title: "Сначала работа команды, потом поля в CMS",
      steps: [
        { title: "Разбираю материалы", text: "Какие разделы меняются, кто за них отвечает и что нельзя публиковать без проверки." },
        { title: "Проектирую модель", text: "Определяю типы материалов, связи, роли и путь от черновика до сайта." },
        { title: "Подключаю и проверяю", text: "Связываю редактор с сайтом, проверяю публикацию и показываю команде её обычные задачи." },
      ],
    },
    related: {
      title: "Посмотреть продукт с двух сторон",
      caseTitle: "Как я проектировал OJ CMS",
      caseText: "Кейс о задаче, интерфейсе и моём вкладе.",
      serviceTitle: "Разработка сайта с CMS",
      serviceText: "Услуга, состав работ и варианты внедрения.",
    },
    final: {
      title: "Покажите, что команда меняет на сайте",
      text: "Расскажите о страницах, материалах и людях, которые их обновляют. Предложу структуру редактора и объясню, что потребуется для рабочего внедрения.",
    },
  },
  en: {
    seoTitle: "OJ CMS on Payload — content, catalog, inquiries and analytics",
    seoDescription: "OJ CMS built on Payload and deployed at KEMZ: catalog and news editing, stored inquiries and analytics through the Yandex Metrika API.",
    hero: {
      eyebrow: "OJ CMS / CONTENT MANAGEMENT",
      title: "Your website should stay easy to update",
      lead: "OJ CMS is my Payload-based system for teams managing a website. At KEMZ it already manages the catalog, news and documents, stores inquiries and displays Yandex Metrika analytics. I tailor sections, fields and permissions to each business.",
      primary: "Try the demo",
      secondary: "Discuss integration",
      note: "The demo is hosted on Vercel and may require a VPN on some networks. Changes stay in your browser only; it is not connected to your website.",
    },
    benefits: {
      label: "01 / FOR YOUR TEAM",
      title: "Update content without a developer queue",
      intro: "Editors need clear actions and a visible result. OJ CMS follows the work of maintaining a website:",
      items: [
        { title: "Pages", text: "Edit headings, copy, images and SEO descriptions in one place." },
        { title: "News", text: "Prepare posts and keep new material in its own section." },
        { title: "Media", text: "Upload images, add descriptions and find files in the library." },
        { title: "Drafts and preview", text: "Save a change, inspect the page and publish with a separate action." },
        { title: "Settings", text: "Update contact details, the site name and navigation without editing code." },
      ],
    },
    workflow: {
      label: "02 / EDITORIAL FLOW",
      title: "Three steps from edit to publish",
      intro: "These are real screens from the OJ CMS demo. Open it and try the same workflow.",
      steps: [
        { number: "01", title: "Find the material", text: "The dashboard shows sections and recent changes.", image: "/projects/oj-cms/dashboard.webp", alt: "Sections and recent changes in the OJ CMS demo" },
        { number: "02", title: "Make an edit", text: "Save a draft and get a warning before leaving with unsaved changes.", image: "/projects/oj-cms/editor.webp", alt: "Page editing in the OJ CMS demo" },
        { number: "03", title: "Check the media", text: "Images live in a library, and a file used by a page cannot be deleted accidentally.", image: "/projects/oj-cms/media.webp", alt: "Media library in the OJ CMS demo" },
      ],
    },
    payload: {
      label: "03 / TECHNOLOGY",
      title: "How OJ CMS and Payload fit together",
      intro: "Payload is an open-source CMS providing server storage, APIs and access rules. OJ CMS builds on it with my own interface, dashboard and team-specific workflows. At KEMZ this setup already handles the catalog, inquiries and Yandex Metrika. The separate browser demo shows the editing workflow without access to factory data.",
      points: [
        { title: "Payload foundation", text: "Open-source collections and fields model pages, posts, products and other content." },
        { title: "OJ CMS layer", text: "I design a focused editor on top: quick access to content, drafts, preview and safeguards against accidental changes." },
        { title: "Roles and versions", text: "A live implementation defines staff access and publishing rules; Payload supports versions and drafts." },
        { title: "Site integration", text: "Published content reaches the bespoke public website through an API." },
      ],
      docs: "Explore Payload documentation",
      docsHref: "https://payloadcms.com/docs/configuration/collections",
    },
    boundary: {
      label: "04 / CURRENT STATE",
      title: "A demo to explore. A deployment to work with.",
      demoTitle: "In the demo today",
      demoText: "Edit pages and news, work with media, save drafts and open previews. Data stays in each visitor's browser. Switching roles illustrates the interface but does not replace server authentication.",
      productionTitle: "Already deployed at KEMZ",
      productionText: "Catalog, categories, news and documents are stored on the Payload server. OJ CMS provides publishing states, website inquiries and Yandex Metrika API analytics. Sections and integrations are configured separately for each client.",
    },
    fit: {
      label: "05 / USE CASES",
      title: "Where a focused editor helps",
      items: [
        { title: "Company website", text: "Update services, cases, news and contact details without a development ticket for every small change." },
        { title: "Catalog", text: "Products, specifications, categories and images need structure and a clear update process." },
        { title: "Content project", text: "Several authors prepare material, review changes and publish under agreed rules." },
      ],
    },
    delivery: {
      label: "06 / IMPLEMENTATION",
      title: "Start with the team's work, then define CMS fields",
      steps: [
        { title: "Map the content", text: "Identify which sections change, who owns them and what needs review before publishing." },
        { title: "Design the model", text: "Define content types, relationships, roles and the path from draft to public site." },
        { title: "Connect and verify", text: "Link the editor to the site, test publication and walk the team through everyday tasks." },
      ],
    },
    related: {
      title: "See the product from both sides",
      caseTitle: "How I designed OJ CMS",
      caseText: "The case study covers the problem, the interface and my role.",
      serviceTitle: "Website development with a CMS",
      serviceText: "Service scope and integration options.",
    },
    final: {
      title: "Show me what your team updates",
      text: "Tell me about your pages, content and editors. I will suggest a content model and explain what a production integration would take.",
    },
  },
} as const;
