export const ojCmsPage = {
  ru: {
    seoTitle: "OJ CMS и Payload — авторский редактор и серверная основа",
    seoDescription: "Как работает демо OJ CMS: страницы, новости, медиа, черновики и предпросмотр. Узнайте, как авторский интерфейс можно связать с Payload при внедрении на сайт.",
    hero: {
      eyebrow: "OJ CMS / УПРАВЛЕНИЕ КОНТЕНТОМ",
      title: "Сайтом удобно управлять и после запуска",
      lead: "OJ CMS — мой интерфейс для команды, которая обновляет сайт. В рабочем демо можно пройти путь от правки страницы до публикации. Для клиентского проекта я отдельно проектирую серверную часть, роли и связь с публичным сайтом.",
      primary: "Попробовать демо",
      secondary: "Обсудить внедрение",
      note: "Демо размещено на Vercel: в некоторых сетях оно может не открыться без VPN. Изменения сохраняются только в вашем браузере; демо не подключено к вашему сайту.",
    },
    benefits: {
      label: "01 / ДЛЯ КОМАНДЫ",
      title: "Контент меняется без очереди к разработчику",
      intro: "Редактору нужны понятные действия и видимый результат. Разделы OJ CMS собраны вокруг обычной работы с сайтом:",
      items: [
        { title: "Страницы", text: "Меняйте заголовки, тексты, изображения и SEO-описания в одном редакторе." },
        { title: "Новости", text: "Готовьте публикации и держите материалы сайта в отдельном разделе." },
        { title: "Медиа", text: "Загружайте изображения, задавайте описания и находите нужный файл в библиотеке." },
        { title: "Черновик и предпросмотр", text: "Сохраните правку, посмотрите страницу и публикуйте её отдельным действием." },
        { title: "Настройки", text: "Обновляйте контакты, название сайта и навигацию без правки кода." },
      ],
    },
    workflow: {
      label: "02 / РАБОЧИЙ СЦЕНАРИЙ",
      title: "От правки до публикации — три понятных шага",
      intro: "Это реальные экраны демонстрации OJ CMS. Откройте её и повторите путь редактора.",
      steps: [
        { number: "01", title: "Найдите материал", text: "На главном экране видны разделы и недавние изменения.", image: "/projects/oj-cms/dashboard.webp", alt: "Обзор разделов и изменений в демонстрации OJ CMS" },
        { number: "02", title: "Внесите правку", text: "Редактор помогает сохранить черновик и предупреждает о несохранённых изменениях.", image: "/projects/oj-cms/editor.webp", alt: "Редактирование страницы в демонстрации OJ CMS" },
        { number: "03", title: "Проверьте медиа", text: "Изображения лежат в библиотеке; использованный на сайте файл нельзя удалить случайно.", image: "/projects/oj-cms/media.webp", alt: "Медиатека в демонстрации OJ CMS" },
      ],
    },
    payload: {
      label: "03 / ТЕХНОЛОГИЯ",
      title: "OJ CMS и Payload: как они связаны",
      intro: "Payload — открытая CMS для хранения контента, API и прав доступа. OJ CMS я проектирую как надстройку над её архитектурой: добавляю свой интерфейс и редакторские сценарии. Нынешнее демо показывает этот интерфейс отдельно: сервер Payload к нему ещё не подключён. Для рабочего сайта я настраиваю Payload, базу данных и публикацию под задачи команды.",
      points: [
        { title: "Основа — Payload", text: "Его коллекции и поля задают структуру страниц, статей, товаров и других материалов. Исходный код открыт." },
        { title: "Слой OJ CMS", text: "Я проектирую поверх этой основы более понятный редактор: быстрый доступ к материалам, черновики, предпросмотр и защиту от случайных действий." },
        { title: "Права и версии", text: "При рабочем внедрении настраиваю доступ сотрудников и порядок публикации; Payload поддерживает версии и черновики." },
        { title: "Связь с сайтом", text: "Через API опубликованный контент попадает в публичный сайт с индивидуальным дизайном." },
      ],
      docs: "Посмотреть возможности Payload",
      docsHref: "https://payloadcms.com/docs/configuration/collections",
    },
    boundary: {
      label: "04 / ЧТО УЖЕ РАБОТАЕТ",
      title: "Демо и рабочее внедрение — разные этапы",
      demoTitle: "Сейчас в демо",
      demoText: "Можно редактировать страницы и новости, работать с медиа, сохранять черновик и открывать предпросмотр. Данные остаются в браузере посетителя; переключение роли показывает интерфейс, но не заменяет серверную авторизацию.",
      productionTitle: "Для вашего сайта",
      productionText: "Нужны отдельные решения: модель контента, серверное хранение, права, подключение публичных страниц, резервное копирование и размещение. Состав определим по тому, что команда действительно обновляет.",
    },
    fit: {
      label: "05 / ПРИМЕНЕНИЕ",
      title: "Когда такой редактор полезен",
      items: [
        { title: "Корпоративный сайт", text: "Команда обновляет услуги, кейсы, новости и контакты без задач на каждую мелкую правку." },
        { title: "Каталог", text: "Товары, характеристики, категории и изображения требуют структуры и понятного процесса обновления." },
        { title: "Контентный проект", text: "Несколько авторов готовят материалы, проверяют изменения и публикуют по согласованным правилам." },
      ],
    },
    delivery: {
      label: "06 / ВНЕДРЕНИЕ",
      title: "Сначала работа команды, потом поля в CMS",
      steps: [
        { title: "Разбираю материалы", text: "Какие разделы меняются, кто за них отвечает и что нельзя публиковать без проверки." },
        { title: "Проектирую модель", text: "Определяю типы материалов, связи, роли и путь от черновика до сайта." },
        { title: "Подключаю и проверяю", text: "Связываю редактор с сайтом, проверяю публикацию и показываю команде её обычные задачи." },
      ],
    },
    related: {
      title: "Посмотреть продукт с двух сторон",
      caseTitle: "Как я проектировал OJ CMS",
      caseText: "Кейс о задаче, интерфейсе и моём вкладе.",
      serviceTitle: "Разработка сайта с CMS",
      serviceText: "Услуга, состав работ и варианты внедрения.",
    },
    final: {
      title: "Покажите, что команда меняет на сайте",
      text: "Расскажите о страницах, материалах и людях, которые их обновляют. Предложу структуру редактора и объясню, что потребуется для рабочего внедрения.",
    },
  },
  en: {
    seoTitle: "OJ CMS and Payload — a custom editor and server foundation",
    seoDescription: "Explore the OJ CMS demo: pages, news, media, drafts and preview. See how its custom editing experience can be connected to Payload for a live website.",
    hero: {
      eyebrow: "OJ CMS / CONTENT MANAGEMENT",
      title: "Your website should stay easy to update",
      lead: "OJ CMS is the editing interface I designed for teams that keep a site current. The working demo takes you from a page edit to publication. Production storage, permissions and the connection to your site are designed for each client project.",
      primary: "Try the demo",
      secondary: "Discuss integration",
      note: "The demo is hosted on Vercel and may require a VPN on some networks. Changes stay in your browser only; it is not connected to your website.",
    },
    benefits: {
      label: "01 / FOR YOUR TEAM",
      title: "Update content without a developer queue",
      intro: "Editors need clear actions and a visible result. OJ CMS follows the work of maintaining a website:",
      items: [
        { title: "Pages", text: "Edit headings, copy, images and SEO descriptions in one place." },
        { title: "News", text: "Prepare posts and keep new material in its own section." },
        { title: "Media", text: "Upload images, add descriptions and find files in the library." },
        { title: "Drafts and preview", text: "Save a change, inspect the page and publish with a separate action." },
        { title: "Settings", text: "Update contact details, the site name and navigation without editing code." },
      ],
    },
    workflow: {
      label: "02 / EDITORIAL FLOW",
      title: "Three steps from edit to publish",
      intro: "These are real screens from the OJ CMS demo. Open it and try the same workflow.",
      steps: [
        { number: "01", title: "Find the material", text: "The dashboard shows sections and recent changes.", image: "/projects/oj-cms/dashboard.webp", alt: "Sections and recent changes in the OJ CMS demo" },
        { number: "02", title: "Make an edit", text: "Save a draft and get a warning before leaving with unsaved changes.", image: "/projects/oj-cms/editor.webp", alt: "Page editing in the OJ CMS demo" },
        { number: "03", title: "Check the media", text: "Images live in a library, and a file used by a page cannot be deleted accidentally.", image: "/projects/oj-cms/media.webp", alt: "Media library in the OJ CMS demo" },
      ],
    },
    payload: {
      label: "03 / TECHNOLOGY",
      title: "How OJ CMS and Payload fit together",
      intro: "Payload is an open-source CMS for content storage, APIs and access rules. I design OJ CMS as a layer on its architecture, adding my own editing interface and workflows. The current demo presents that interface separately: it is not yet connected to a Payload server. For a live site, I configure Payload, a database and publishing around the team's needs.",
      points: [
        { title: "Payload foundation", text: "Open-source collections and fields model pages, posts, products and other content." },
        { title: "OJ CMS layer", text: "I design a focused editor on top: quick access to content, drafts, preview and safeguards against accidental changes." },
        { title: "Roles and versions", text: "A live implementation defines staff access and publishing rules; Payload supports versions and drafts." },
        { title: "Site integration", text: "Published content reaches the bespoke public website through an API." },
      ],
      docs: "Explore Payload documentation",
      docsHref: "https://payloadcms.com/docs/configuration/collections",
    },
    boundary: {
      label: "04 / CURRENT STATE",
      title: "The demo and a live integration are different stages",
      demoTitle: "In the demo today",
      demoText: "Edit pages and news, work with media, save drafts and open previews. Data stays in each visitor's browser. Switching roles illustrates the interface but does not replace server authentication.",
      productionTitle: "For your website",
      productionText: "A live deployment needs a content model, server storage, permissions, a link to public pages, backups and hosting. The scope depends on what your team actually updates.",
    },
    fit: {
      label: "05 / USE CASES",
      title: "Where a focused editor helps",
      items: [
        { title: "Company website", text: "Update services, cases, news and contact details without a development ticket for every small change." },
        { title: "Catalog", text: "Products, specifications, categories and images need structure and a clear update process." },
        { title: "Content project", text: "Several authors prepare material, review changes and publish under agreed rules." },
      ],
    },
    delivery: {
      label: "06 / IMPLEMENTATION",
      title: "Start with the team's work, then define CMS fields",
      steps: [
        { title: "Map the content", text: "Identify which sections change, who owns them and what needs review before publishing." },
        { title: "Design the model", text: "Define content types, relationships, roles and the path from draft to public site." },
        { title: "Connect and verify", text: "Link the editor to the site, test publication and walk the team through everyday tasks." },
      ],
    },
    related: {
      title: "See the product from both sides",
      caseTitle: "How I designed OJ CMS",
      caseText: "The case study covers the problem, the interface and my role.",
      serviceTitle: "Website development with a CMS",
      serviceText: "Service scope and integration options.",
    },
    final: {
      title: "Show me what your team updates",
      text: "Tell me about your pages, content and editors. I will suggest a content model and explain what a production integration would take.",
    },
  },
} as const;
