import Image from "next/image";
import Link from "next/link";
import { privacyBlogPath } from "@/content/blog";
import styles from "../blog.module.css";

export function CatalogArticle({ locale }: { locale: string }) {
  const en = locale === "en";
  return <article className={`shell ${styles.article}`}>
    <aside className={styles.toc}>
      <p>{en ? "IN THIS ARTICLE" : "В ЭТОЙ СТАТЬЕ"}</p>
      <a href="#catalog-language">{en ? "How buyers search" : "Как ищут покупатели"}</a>
      <a href="#catalog-find">{en ? "Search and filters" : "Поиск и фильтры"}</a>
      <a href="#catalog-card">{en ? "Model page" : "Карточка модели"}</a>
      <a href="#catalog-enquiry">{en ? "Enquiry" : "Заявка"}</a>
      <a href="#catalog-operations">{en ? "Content and SEO" : "Контент и поиск"}</a>
      <a href="#catalog-check">{en ? "Launch checklist" : "Проверка перед запуском"}</a>
    </aside>
    <div className={styles.articleBody}>
      {en ? <EnglishContent locale={locale} /> : <RussianContent locale={locale} />}
    </div>
  </article>;
}

function ProcessFigure({ en }: { en: boolean }) {
  return <figure className={styles.catalogFigure}>
    <div className={styles.catalogFigureArt}>
      <Image src="/blog/catalog-equipment-flow.webp" alt={en ? "Oleg connects equipment specifications with an enquiry at a workbench" : "Маскот Олега связывает характеристики электродвигателя с заявкой на рабочем столе"} width={1672} height={941} sizes="(max-width: 760px) 92vw, 740px" loading="lazy" />
    </div>
    <figcaption>{en ? "The useful route: find a model, verify its parameters, send an enquiry with context." : "Полезный маршрут: найти модель, сверить параметры, отправить заявку с контекстом."}</figcaption>
  </figure>;
}

function ProjectFigure({ en, locale }: { en: boolean; locale: string }) {
  return <figure className={styles.catalogFigure}>
    <Link href={`/${locale}/work/aokemz`} className={styles.catalogProjectLink}>
      <Image src="/projects/aokemz-v2.webp" alt={en ? "KEMZ website homepage with an entry point to the equipment catalog" : "Главная страница сайта КЭМЗ с переходом в каталог оборудования"} width={1265} height={712} sizes="(max-width: 760px) 92vw, 740px" loading="lazy" />
    </Link>
    <figcaption>{en ? "The live KEMZ project. The case study explains the catalog and product-page decisions." : "Реальный проект КЭМЗ. В кейсе разбираю решения для каталога и карточек моделей."} <Link href={`/${locale}/work/aokemz`}>{en ? "View the case" : "Смотреть кейс"} ↗</Link></figcaption>
  </figure>;
}

function RussianContent({ locale }: { locale: string }) {
  return <>
    <section className={styles.prose}><p className={styles.dropLead}>В промышленном каталоге посетитель редко выбирает по одной красивой фотографии. У него может быть обозначение модели, набор характеристик или задача без точного названия оборудования. Сайт должен помочь ему проверить вариант и обратиться с предметным запросом.</p><p>Ниже — решения, которые я применял при работе над сайтом КЭМЗ. Это разбор подхода, а не обещание роста заявок: без данных о продажах такого вывода сделать нельзя.</p></section>
    <section id="catalog-language" className={styles.prose}><p className={styles.chapter}>01 / ЯЗЫК ПОКУПАТЕЛЯ</p><h2>Начните с вопросов закупки, а не с папок склада</h2><p>Перед проектированием КЭМЗ я обсуждал сайт с руководителем, маркетингом, производством и продажами. Важно было понять, какие названия используют клиенты, какие параметры проверяют и в какой момент им нужен человек. Эта работа определяет структуру лучше, чем произвольное меню «Продукция» с длинным списком моделей.</p><p>Для одной аудитории отправная точка — тип оборудования, для другой — известная маркировка, для третьей — мощность или область применения. Названия разделов, синонимы в поиске и состав карточки стоит собирать из таких сценариев. Если покупатели называют изделие иначе, чем внутренний справочник предприятия, это различие нужно учесть в интерфейсе.</p></section>
    <section id="catalog-find" className={styles.prose}><p className={styles.chapter}>02 / ПОИСК</p><h2>Дайте два пути: через категорию и через модель</h2><p>Категории помогают тому, кто ещё сравнивает варианты. Поиск по обозначению нужен человеку, который уже знает модель. Фильтры полезны, если показывают действительно различающие характеристики: например, мощность, напряжение, исполнение. Единицы измерения должны быть видны рядом со значениями, а выбранные фильтры — легко сбрасываться, в том числе на телефоне.</p><p>В каталоге КЭМЗ мы предусмотрели разделы оборудования, фильтры и переход к отдельной модели. В кейсе показаны примеры экранов и сам подход к их построению. <Link href={`/${locale}/work/aokemz`}>Посмотреть проект КЭМЗ ↗</Link></p></section>
    <ProcessFigure en={false} />
    <section id="catalog-card" className={styles.prose}><p className={styles.chapter}>03 / КАРТОЧКА</p><h2>Карточка модели — рабочий технический документ</h2><p>На странице модели нужны точное обозначение, понятное назначение, проверенные характеристики с единицами измерения, изображения и документация, если предприятие готово её публиковать. Параметры лучше подавать таблицей или короткими группами: так можно быстро сверить спецификацию с задачей, а не вычитывать рекламный абзац.</p><p>Не стоит заполнять пробелы догадками. Если для конкретной модели нет чертежа, актуального срока поставки или цены, лучше честно предложить запросить эти данные. Для сложного оборудования кнопка «Уточнить параметры» может быть полезнее фиктивной кнопки «Купить».</p><p>У каждой значимой модели должен быть постоянный адрес и связь с категорией. Тогда на неё можно отправить ссылку из письма, а поисковая система видит отдельную страницу с собственным содержимым. <a href="https://developers.google.com/search/docs/specialty/ecommerce/designing-a-url-structure-for-ecommerce-sites" target="_blank" rel="noreferrer">Google рекомендует продуманную структуру URL</a> и предупреждает о проблемах от множества параметрических копий страниц.</p></section>
    <ProjectFigure en={false} locale={locale} />
    <section id="catalog-enquiry" className={styles.prose}><p className={styles.chapter}>04 / ЗАЯВКА</p><h2>Заявка должна продолжать выбор</h2><p>Если человек нажимает «Запросить предложение» на карточке, форма уже должна знать, какую модель он смотрел. Ему остаётся описать условия применения или прикрепить техническое задание, если такая возможность есть. Повторно спрашивать название модели и заставлять искать почту отдела продаж — лишние шаги.</p><p>Набор полей определяется реальным процессом продаж. Для первого контакта обычно достаточно способа связи и сути запроса; специфические параметры можно уточнить в разговоре. При этом маршрут данных формы — получатель, хранение, доступы и согласие — надо продумать до публикации. Я отдельно разобрал это в <Link href={privacyBlogPath(locale)}>статье о 152‑ФЗ и заявках</Link>.</p></section>
    <section id="catalog-operations" className={styles.prose}><p className={styles.chapter}>05 / ПОСЛЕ ЗАПУСКА</p><h2>Каталог должен обновляться и оставаться понятным для поиска</h2><p>Модельный ряд меняется. Команде нужен редактор, где можно добавить изделие, поправить характеристики, заменить изображение и связать модель с категорией без ручной правки кода. Сайт КЭМЗ разработан на Next.js и React; для работы с контентом я подключил OJ CMS на базе Payload. Продукция, категории, новости и документы редактируются в одной панели. Заявки сохраняются в CMS до отправки письма, а посещаемость и популярные страницы доступны через API Яндекс Метрики. Само название CMS не делает каталог удобным — важнее состав полей и права редакторов.</p><p>Для поиска нужны доступные страницы категорий и моделей, осмысленные заголовки и внутренние ссылки. Фильтры не стоит автоматически превращать в тысячи почти одинаковых индексируемых URL. Публиковать отдельную посадочную страницу имеет смысл, когда за сочетанием параметров стоит реальный запрос и можно дать уникальную, полезную информацию. Это архитектурное решение, а не гарантия позиции.</p></section>
    <CmsFigure en={false} />
    <section id="catalog-check" className={styles.prose}><p className={styles.chapter}>06 / ПЕРЕД ЗАПУСКОМ</p><h2>Проверьте маршрут на живой задаче</h2><ol className={styles.catalogChecklist}><li>Найдите модель по точному обозначению и по категории.</li><li>С телефона сравните ключевые характеристики и сбросьте фильтры.</li><li>Откройте прямую ссылку на модель без перехода через главную.</li><li>Отправьте запрос: проверьте, дошли ли модель и сообщение до ответственного.</li><li>Попросите редактора обновить характеристику и посмотрите опубликованную страницу.</li></ol><p>Если какой-то шаг требует догадаться, где продолжать, каталог ещё не закончен. <Link href={`/${locale}/services/product-catalogues`}>Как я проектирую сайты-каталоги ↗</Link></p></section>
  </>;
}

function EnglishContent({ locale }: { locale: string }) {
  return <>
    <section className={styles.prose}><p className={styles.dropLead}>Industrial buyers rarely choose from a photograph alone. They may have a model code, a list of specifications, or a task without an exact product name. The catalog should help them verify an option and make a useful enquiry.</p><p>These are decisions from my work on the KEMZ website. This is a design account, not a claim that enquiries increased: that would require sales data.</p></section>
    <section id="catalog-language" className={styles.prose}><p className={styles.chapter}>01 / BUYER LANGUAGE</p><h2>Start with procurement questions, not warehouse folders</h2><p>Before designing KEMZ, I spoke with leadership, marketing, production and sales about the names customers use, the parameters they check and when they need a person. Those conversations shape the information architecture more reliably than a long, arbitrary “Products” menu.</p><p>One buyer starts with an equipment type, another with a model designation, a third with power or application. Category names, search synonyms and product-page fields should reflect those routes. Internal naming and buyer language do not always match.</p></section>
    <section id="catalog-find" className={styles.prose}><p className={styles.chapter}>02 / FIND</p><h2>Support both categories and exact models</h2><p>Categories serve buyers comparing options. Model-code search serves those who already know what they need. Filters help when they expose meaningful differences, such as power, voltage or configuration. Show units alongside values and make selected filters easy to remove on mobile too.</p><p>For KEMZ, we planned equipment sections, filters and individual model pages. <Link href={`/${locale}/work/aokemz`}>Explore the KEMZ case ↗</Link></p></section>
    <ProcessFigure en />
    <section id="catalog-card" className={styles.prose}><p className={styles.chapter}>03 / MODEL PAGE</p><h2>Treat the model page as a technical document</h2><p>Give each model an exact name, a clear purpose, verified specifications with units, useful images and documentation where available. Group parameters so a buyer can scan them against a requirement instead of reading a promotional paragraph.</p><p>Do not fill gaps with guesses. If a drawing, delivery estimate or price is unavailable, invite a specific request. For complex equipment, “Ask about this model” may be more useful than an artificial “Buy now”.</p><p>Important models need stable URLs and links from their categories. They become shareable from email and understandable to search engines. <a href="https://developers.google.com/search/docs/specialty/ecommerce/designing-a-url-structure-for-ecommerce-sites" target="_blank" rel="noreferrer">Google&apos;s URL guidance</a> also explains the duplication risks of uncontrolled parameter URLs.</p></section>
    <ProjectFigure en locale={locale} />
    <section id="catalog-enquiry" className={styles.prose}><p className={styles.chapter}>04 / ENQUIRY</p><h2>Let the enquiry continue the selection</h2><p>When someone requests a quote from a model page, the form should carry that model with it. The visitor can then describe the application or attach a brief if the workflow supports it. Asking them to type the model again or hunt for a sales email adds unnecessary work.</p><p>Form fields should match the sales process. For first contact, a reply channel and a useful question may be enough. Decide where enquiries go, who can access them and how long they remain stored before launch. For sites handling Russian personal data, see my <Link href={privacyBlogPath(locale)}>152-FZ checklist</Link>.</p></section>
    <section id="catalog-operations" className={styles.prose}><p className={styles.chapter}>05 / OPERATIONS</p><h2>Keep products editable and search pages useful</h2><p>Product lines change. Editors need to add models, correct specifications, replace images and assign categories without code changes. KEMZ runs on Next.js and React with OJ CMS on Payload. Products, categories, news and documents are edited in one panel. Inquiries are stored before email notifications are sent, while the Yandex Metrika API supplies traffic and popular-page data. The CMS brand is less important than the fields and permissions it provides.</p><p>Search visibility also depends on accessible category and model pages, informative headings and internal links. Do not turn every filter combination into another near-duplicate indexable URL. A separate landing page makes sense when it answers a real buyer question with distinct information. No framework or URL rule guarantees a ranking.</p></section>
    <CmsFigure en />
    <section id="catalog-check" className={styles.prose}><p className={styles.chapter}>06 / BEFORE LAUNCH</p><h2>Test the route with a real task</h2><ol className={styles.catalogChecklist}><li>Find a model by exact designation and by category.</li><li>Compare key specifications and clear filters on a phone.</li><li>Open a model&apos;s direct URL without visiting the homepage.</li><li>Send an enquiry and verify that the model and message reach the right person.</li><li>Ask an editor to update a specification and check the published page.</li></ol><p>If a step requires guesswork, the catalog needs more work. <Link href={`/${locale}/services/product-catalogues`}>My approach to product catalogs ↗</Link></p></section>
  </>;
}

function CmsFigure({ en }: { en: boolean }) {
  return <figure className={styles.catalogFigure}><Image className={styles.catalogCmsImage} src="/projects/kemz/cms/dashboard.webp" alt={en ? "Live KEMZ OJ CMS dashboard for products, news and inquiries" : "Реальная панель OJ CMS для КЭМЗ: продукция, новости и заявки"} width={1265} height={723} sizes="(max-width: 760px) 92vw, 740px" loading="lazy" /><figcaption>{en ? "October 2026 update: OJ CMS on Payload deployed at KEMZ." : "Дополнено в октябре 2026: рабочее внедрение OJ CMS на базе Payload для КЭМЗ."}</figcaption></figure>;
}
