import Link from "next/link";
import styles from "../blog.module.css";

const law = "https://www.consultant.ru/document/cons_doc_LAW_61801/";
const fines = "https://www.consultant.ru/document/cons_doc_LAW_34661/1f421640c6775ff67079ebde06a7d2f6d17b96db/";

export function PrivacyArticle({ locale }: { locale: string }) {
  if (locale === "en") return <article className={`shell ${styles.article}`}><aside className={styles.toc}><p>IN THIS ARTICLE</p><a href="#en-data">What counts as data</a><a href="#en-check">Prelaunch review</a><a href="#en-risk">Liability</a></aside><div className={styles.articleBody}>
    <section id="en-data" className={styles.prose}><p className={styles.chapter}>01 / THE QUESTION</p><h2>A contact form is already a data flow</h2><p className={styles.dropLead}>A name, email, phone number, message and analytics identifiers may relate to a person. A website owner should know why each item is collected, where it travels and who can access it.</p><p>For projects aimed at Russian users, Federal Law No. 152-FZ applies to personal-data processing. The exact duties depend on the operator, processing grounds and services used. This article is a practical starting point, not a legal opinion for a particular business.</p></section>
    <section id="en-check" className={styles.prose}><p className={styles.chapter}>02 / BEFORE LAUNCH</p><h2>Review the whole path of an enquiry</h2><p>Map fields, analytics, inboxes, CRM, hosting and third parties. Define purposes and lawful grounds. Publish an accessible processing policy. When relying on consent, make it specific and separate from other documents. Check whether the operator must notify Roskomnadzor before processing, where Russian citizens’ data is first recorded and stored, and how access, retention, deletion and incident response work. A checkbox alone does not solve the entire task.</p><p>Read my <Link href={`/${locale}/legal/privacy`}>processing policy</Link>, <Link href={`/${locale}/legal/consent`}>consent text</Link> and <Link href={`/${locale}/legal/cookies`}>cookie policy</Link> as examples of site documents, then adapt your own documents to your actual data flows.</p></section>
    <section id="en-risk" className={styles.prose}><p className={styles.chapter}>03 / RESPONSIBILITY</p><h2>The owner remains responsible</h2><p>A developer can build the form and consent interface; the operator determines purposes and grounds and remains responsible for compliance. Article 13.11 of the Russian Administrative Offences Code provides fines for particular violations, including failure to publish a required policy or notify the authority when required. Check the applicable provision and current amount for your legal status.</p><p className={styles.sourceLine}>Sources: <a href={law} target="_blank" rel="noreferrer">Federal Law No. 152-FZ</a> · <a href={fines} target="_blank" rel="noreferrer">Administrative Offences Code, Article 13.11</a>. Reviewed 29 September 2026.</p></section>
  </div></article>;

  return <article className={`shell ${styles.article}`}><aside className={styles.toc}><p>В ЭТОЙ СТАТЬЕ</p><a href="#data">Какие данные собирает сайт</a><a href="#check">Что проверить</a><a href="#responsibility">Кто отвечает</a><a href="#fines">Штрафы</a><a href="#faq">Частые вопросы</a></aside><div className={styles.articleBody}>
    <section id="data" className={styles.prose}><p className={styles.chapter}>01 / С ЧЕГО НАЧАТЬ</p><h2>Форма заявки — уже обработка данных</h2><p className={styles.dropLead}>Человек оставляет имя, телефон, почту и сообщение. Сайт отправляет их в почту или CRM, иногда добавляет данные аналитики. Владельцу важно понимать весь этот путь, даже если форму сделал подрядчик.</p><p>Персональные данные — сведения, которые относятся к определённому или определяемому человеку. Закон № 152‑ФЗ касается не только больших интернет-магазинов: простая форма связи тоже требует разобраться с целями, основанием и защитой обработки. Конкретный набор обязанностей зависит от того, кто оператор, какие данные и каким способом обрабатываются.</p></section>
    <div className={styles.quote}><span>«</span><p>Красивый сайт не заканчивается на кнопке «Отправить». Важно знать, что происходит с заявкой после нажатия.</p></div>
    <section id="check" className={styles.prose}><p className={styles.chapter}>02 / ЧЕК-ЛИСТ ПЕРЕД ЗАПУСКОМ</p><h2>Что проверить на своём сайте</h2><p><strong>Карта данных.</strong> Выпишите поля форм, аналитику, чаты, рассылки, хостинг, почтовый сервис и CRM. Отметьте, кто получает доступ к заявкам и где они хранятся. Собирайте только то, что нужно для указанной цели.</p><p><strong>Основание и согласие.</strong> Для каждой цели определите правовое основание. Если используете согласие, оно должно быть конкретным, информированным и оформленным отдельно от других подтверждаемых документов. Не ставьте галочку за посетителя заранее и сохраняйте возможность подтвердить получение согласия.</p><p><strong>Документы и интерфейс.</strong> Разместите доступную <Link href={`/${locale}/legal/privacy`}>политику обработки персональных данных</Link> и понятный текст <Link href={`/${locale}/legal/consent`}>согласия для формы</Link>. Опишите реальные цели, состав данных, получателей, сроки и способ обращения к оператору. Для необязательной аналитики проверьте настройки загрузки и <Link href={`/${locale}/legal/cookies`}>cookie-политику</Link>.</p><p><strong>Роскомнадзор и инфраструктура.</strong> Проверьте, нужно ли до начала обработки подать уведомление в Роскомнадзор: для автоматизированной формы исключения обычно узкие. Отдельно разберите размещение баз с данными граждан РФ, передачи сторонним сервисам, доступы сотрудников, резервные копии, удаление и действия при утечке.</p></section>
    <div className={styles.platformNotes}><div><span>01 / ДО ФОРМЫ</span><h3>Понятная цель</h3><p>Посетитель видит, зачем вы просите контакты и куда обратиться по вопросам обработки.</p></div><div><span>02 / ПОСЛЕ ОТПРАВКИ</span><h3>Контроль доступа</h3><p>Заявка попадает только к тем, кому она нужна для ответа; сроки хранения не берутся «навсегда» по умолчанию.</p></div><div><span>03 / ПОСЛЕ ЗАПУСКА</span><h3>Актуальность</h3><p>Новая CRM, рассылка или счётчик меняют схему обработки. Документы и настройки надо пересматривать вместе с сайтом.</p></div></div>
    <section id="responsibility" className={styles.prose}><p className={styles.chapter}>03 / КТО ОТВЕЧАЕТ</p><h2>Ответственность остаётся у владельца сайта</h2><p>Подрядчик может сверстать форму, настроить отправку и подсказать, какие документы нужны. Но цели обработки и правовые основания определяет оператор данных. В быстрой сборке сайта — у фрилансера или студии — этот этап иногда выпадает из задачи. Поэтому стоит включать проверку персональных данных в бриф и приёмку, а не считать, что галочка автоматически решает всё.</p><p>В своих проектах я связываю интерфейс формы, текст согласия, настройки аналитики и маршрут заявки. Юридическую оценку конкретной схемы обработки лучше согласовать со специалистом по персональным данным.</p></section>
    <section id="fines" className={styles.prose}><p className={styles.chapter}>04 / РИСКИ</p><h2>За нарушения предусмотрены штрафы</h2><p>Статья 13.11 КоАП РФ разделяет разные нарушения. Например, за отсутствие опубликованной политики для юридического лица предусмотрено <strong>30–60 тыс. ₽</strong>; за неподачу обязательного уведомления об обработке данных — <strong>100–300 тыс. ₽</strong>. Для граждан, должностных лиц и ИП суммы и составы могут отличаться. За утечки и повторные нарушения санкции могут быть значительно выше. Это не «штраф за любой сайт без галочки»: ответственность зависит от конкретного состава нарушения.</p><p>Проверка перед запуском обычно дешевле исправления формы, документов и маршрута заявок после претензии. Начните с фактической схемы данных, а затем приводите документы и интерфейс в соответствие с ней.</p><p className={styles.sourceLine}>Источники и дата проверки — 29 сентября 2026 года: <a href={law} target="_blank" rel="noreferrer">Федеральный закон № 152‑ФЗ</a> (статьи 5, 6, 9, 18, 18.1, 19, 22); <a href={fines} target="_blank" rel="noreferrer">КоАП РФ, статья 13.11</a> (части 3 и 10). Суммы и редакцию закона проверяйте на дату применения.</p></section>
    <section id="faq" className={`${styles.prose} ${styles.faq}`}><p className={styles.chapter}>05 / ВОПРОСЫ</p><h2>Коротко о главном</h2><h3>Достаточно ли ссылки на политику под формой?</h3><p>Нет. Политика объясняет обработку, но её содержание должно совпадать с реальным движением данных. Для обработки может требоваться отдельное согласие или другое законное основание; также важны уведомление, безопасность и правила хранения.</p><h3>Если заявки идут только на почту, 152‑ФЗ всё равно касается сайта?</h3><p>Да, способ доставки не отменяет обработку данных. Проверьте, что собираете, кто получает письма, где они остаются и как удаляются.</p><h3>Можно ли поручить это разработчику?</h3><p>Разработчик реализует техническую часть и может подготовить схему данных. Решения об основаниях, целях и документах принимает оператор; для правовой проверки полезен профильный юрист.</p><p>Если вы готовите новый проект, посмотрите мои <Link href={`/${locale}/services/landing-pages`}>лендинги</Link>, <Link href={`/${locale}/services/web-applications`}>веб-приложения</Link> и <Link href={`/${locale}/work`}>кейсы</Link>: вопросы формы, аналитики и хранения данных лучше решать вместе с архитектурой сайта.</p></section>
  </div></article>;
}
